### ISSUE TITLE
Video link was not found 

### ISSUE THREAD

**Issue by QuantumLiu** [msraig/self-augmented-net#2]
Hello！
Your video [link](http://msraig.info/~sanet/sanet.mov) was not found, would you please fix it?
Thanks a lot!
> Not Found
> 
> The requested URL /~sanet/sanet.mov was not found on this server.
> 
> Apache/2.2.15 (CentOS) Server at msraig.info Port 80

**Comment by doyleconan** [comment]
Thanks for checking, the link now fixed.
Best Regards.
