### ISSUE TITLE
SA-SVBRDF-Net

### ISSUE THREAD

**Issue by Brave111** [msraig/self-augmented-net#3]
您好，我看到您的渲染代码里有m,l,v,o中v和o分别代表什么啊？

**Comment by pableeto** [comment]
We used a set of pre-defined lighting rotations (id denoted as v) and cropping positions (id denoted as o) when generating dataset for training.

**Comment by Brave111** [comment]
那 l 呢？为什么lighting里面有98副不同场景下的图片啊？是用来怎么渲染的呢？
